<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="params.xacro"/>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_link"/>
        <origin xyz="0.0 0.0 ${height+(2*wheelrad)+0.05}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="0.05" h="0.04"/>
    </link>

    <gazebo reference="laser_link">
        <material>Gazebo/Red</material>
        
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose> <!-- Origen de sensor -->
            <visualize> true </visualize> <!-- Visualizacion de sensor -->
            <update_rate> 10 </update_rate> <!-- 1 Hz -->
            <ray> <!-- Parametros de sensor virtual -->
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>10</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>